// Exports the Sepolia workflow runs as judge-facing evidence:
//   evidence/README.md        one row per run: workflow, trigger, capabilities, outcome, Sepolia tx
//   evidence/logs/<n>-<handler>.log   the full `cre workflow simulate --broadcast` output of each run
// Usage: bun scripts/export-evidence.ts

const ROOT = new URL('../', import.meta.url).pathname
const state = await Bun.file(`${ROOT}services/rails/data/state.sepolia.json`).json()
const dep = await Bun.file(`${ROOT}contracts/deployments/sepolia.json`).json()
const runs: any[] = [...state.runs].filter((r) => r.status === 'success').sort((a, b) => a.id - b.id)
const ETHERSCAN = 'https://sepolia.etherscan.io'

const CAPS: Record<string, string> = {
  'verify-and-list': 'Confidential Workflow (TEE, `handlerInTee`), HTTP in enclave, EVM read (Chainlink EUR/USD Data Feed), EVM write',
  'verify-lender': 'Confidential HTTP (Vault DON secret), EVM write',
  'credit-fiat-deposit': 'Confidential HTTP, EVM read (Chainlink EUR/USD + market), EVM write',
  'disburse-on-funded': 'EVM log trigger, HTTP POST with consensus, EVM read/write',
  'confirm-repayment': 'HTTP trigger, `runInNodeMode` over two sources with consensus, EVM read/write',
  'redeem-fiat-lenders': 'EVM log trigger, HTTP with consensus, EVM read/write',
  'watch-and-reconcile': 'Cron trigger, EVM read, HTTP with consensus, EVM write',
}
const TRIGGER: Record<string, string> = { http: 'HTTP', 'evm-log': 'EVM log', cron: 'Cron' }

function outcome(r: any): string {
  const d = r.resultData ?? {}
  switch (r.handler) {
    case 'verify-and-list':
      return d.listed ? `Listed ${d.docNumber}: grade ${d.grade}, APR ${d.aprBps / 100}%, advance $${Number(d.target) / 1e6}${d.currency === 'EUR' ? `, EUR/USD ${Number(d.fxRateE8) / 1e8}` : ''}` : `Rejected ${d.docNumber}: ${d.reason}`
    case 'verify-lender':
      return `KYC ${d.verified ? 'verified' : 'not approved'}: ${d.lenderId}`
    case 'credit-fiat-deposit':
      return `Credited $${Number(d.stablecoins) / 1e6} for ${d.fiat}; on-ramp ${Number(d.providerRate) / 1e8} vs Chainlink ${Number(d.chainlinkRate) / 1e8}`
    case 'disburse-on-funded':
      return `Paid $${Number(d.amount) / 1e6} to the business (${d.payoutRef}), loan ${d.loanId}`
    case 'confirm-repayment':
      return `Repayment $${Number(d.amount) / 1e6} from ${d.payer}, confirmed by ${d.sources?.join(' and ')}`
    case 'redeem-fiat-lenders':
      return (d.redeemed ?? []).map((x: any) => `${x.lender} paid $${Number(x.payout) / 1e6} (${x.payoutRef})`).join('; ') || 'no fiat lenders'
    case 'watch-and-reconcile': {
      const changes = (d.statusChanges ?? []).map((c: any) => `loan ${c.loanId} ${c.status}, business frozen`).join('; ')
      return `Reconciliation ${d.reconciliation?.ok ? 'passed' : 'FAILED (funding paused)'}${changes ? `; ${changes}` : ''}`
    }
  }
  return ''
}

function txs(r: any): string[] {
  const d = r.resultData ?? {}
  return [d.tx, d.reconciliation?.tx, ...(d.redeemed ?? []).map((x: any) => x.tx), ...(d.statusChanges ?? []).map((x: any) => x.tx)].filter(Boolean)
}

await Bun.$`mkdir -p ${ROOT}evidence/logs`
const rows: string[] = []
for (const r of runs) {
  const file = `logs/${String(r.id).padStart(2, '0')}-${r.handler}.log`
  await Bun.write(`${ROOT}evidence/${file}`, `${r.logs.join('\n')}\n`)
  const links = txs(r).map((h) => `[${h.slice(0, 10)}…](${ETHERSCAN}/tx/${h})`).join('<br>')
  rows.push(`| ${r.id} | \`${r.workflow}\` · ${r.handler} | ${TRIGGER[r.trigger] ?? r.trigger} | ${CAPS[r.handler] ?? ''} | ${outcome(r)} | ${links || '(no write: rejected)'} | [log](${file}) |`)
}

const md = `# Evidence: CRE workflow simulations on Ethereum Sepolia

Every run below is \`cre workflow simulate <workflow> --target sepolia --broadcast\` (CRE CLI v1.37),
executed by the app as the loan moved through its lifecycle. Each onchain write is a signed CRE report
delivered through the Sepolia **MockKeystoneForwarder** (\`${dep.forwarder}\`) to the market contract.

| Contract | Address |
|---|---|
| TradeflowMarket (CRE receiver) | [\`${dep.market}\`](${ETHERSCAN}/address/${dep.market}) |
| LoanNotes (KYC-gated ERC-1155) | [\`${dep.notes}\`](${ETHERSCAN}/address/${dep.notes}) |
| Test stablecoin (tUSDC) | [\`${dep.stablecoin}\`](${ETHERSCAN}/address/${dep.stablecoin}) |

| # | Workflow · handler | Trigger | CRE capabilities used | Outcome | Sepolia transaction | Log |
|---|---|---|---|---|---|---|
${rows.join('\n')}

Generated by \`scripts/export-evidence.ts\` from the app's run history.
`
await Bun.write(`${ROOT}evidence/README.md`, md)
console.log(`wrote evidence/README.md with ${runs.length} runs`)
